version: '3.5'
networks:
  devtools:
    name: devtools
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.2
    container_name: "zookeeper"
    ports:
      - "2181:2181"
    restart: always
    networks:
      - devtools
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka:4.1.2
    container_name: "kafka"
    volumes:
      - ./certs:/etc/kafka/secrets
    ports:
      - "9092:9092"
    restart: always
    networks:
      - devtools
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=10
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - JMX_PORT=8004

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: "elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - devtools
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    container_name: "kibana"
    ports:
      - "5601:5601"
    networks:
      - devtools
    depends_on:
      - elasticsearch